SiCED/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiCED.Models;
using PagedList;

namespace SiCED.Controllers
{
    public class AlunoController : Controller
    {
        private ContextoEF db = new ContextoEF();

        public ActionResult ConsultarAluno(int? pagina, string nomeAluno = null)
        {
            int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;
            var aluno = new Object();

            if (!String.IsNullOrEmpty(nomeAluno))
            {
                aluno = db.Alunos
                    .Where(c => c.Nome.ToUpper().Contains(nomeAluno.ToUpper()))
                    .OrderBy(c => c.Nome)
                    .ToPagedList(numeroPagina, tamanhoPagina);
            }
            else
            {
                aluno = db.Alunos.OrderBy(p => p.Nome).ToPagedList(numeroPagina, tamanhoPagina);
            }
            return View("Index", aluno);
        }

        // GET: Aluno
        public ActionResult Index(string ordenacao, int? pagina)
        {
            try
            {
                ViewBag.OrdenacaoAtual = ordenacao;
                ViewBag.NomeParam = String.IsNullOrEmpty(ordenacao) ? "Nome_desc" : "";
                ViewBag.CpfParam = ordenacao == "CPF" ? "CPF_desc" : "CPF";

                var alunos = from c in db.Alunos select c;

                int tamnahoPagina = 5;
                int numeroPagina = pagina ?? 1;

                switch (ordenacao)
                {
                    case "Nome_desc":
                        alunos = alunos.OrderByDescending(s => s.Nome);
                        break;
                    case "CPF":
                        alunos = alunos.OrderBy(s => s.CPF);
                        break;
                    case "CPF_desc":
                        alunos = alunos.OrderByDescending(s => s.CPF);
                        break;
                    default:
                        alunos = alunos.OrderBy(s => s.Nome);
                        break;
                }

                //var alunos = db.Alunos.Include(a => a.Responsaveis);
                // return View(db.Alunos.OrderBy(p => p.Nome).ToPagedList(numeroPagina, tamnahoPagina));
                return View(alunos.ToPagedList(numeroPagina, tamnahoPagina));
            }

            catch(Exception err)
            {
                ViewBag.DetalheErros = err.Message.ToString();
                return View("Error");
            }
        }

        // GET: Aluno/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        // GET: Aluno/Create
        public ActionResult Create()
        {
            ViewBag.ResponsavelId = new SelectList(db.Responsaveis, "ResponsavelId", "Nome");
            return View();
        }

        // POST: Aluno/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlunoId,ResponsavelId,Nome,CPF,Celular,DataNascimento")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Alunos.Add(aluno);
                db.SaveChanges();
                TempData["Mensagem"] = "Aluno cadastrado com sucesso! ";
                return RedirectToAction("Index");
            }

            ViewBag.ResponsavelId = new SelectList(db.Responsaveis, "ResponsavelId", "Nome", aluno.ResponsavelId);
            return View(aluno);
        }

        // GET: Aluno/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResponsavelId = new SelectList(db.Responsaveis, "ResponsavelId", "Nome", aluno.ResponsavelId);
            return View(aluno);
        }

        // POST: Aluno/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlunoId,ResponsavelId,Nome,CPF,Celular,DataNascimento")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aluno).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Aluno atualizado com sucesso! ";
                return RedirectToAction("Index");
            }
            ViewBag.ResponsavelId = new SelectList(db.Responsaveis, "ResponsavelId", "Nome", aluno.ResponsavelId);
            return View(aluno);
        }

        // GET: Aluno/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aluno aluno = db.Alunos.Find(id);
            if (aluno == null)
            {
                return HttpNotFound();
            }
            return View(aluno);
        }

        // POST: Aluno/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Aluno aluno = db.Alunos.Find(id);
            db.Alunos.Remove(aluno);
            db.SaveChanges();
            TempData["Mensagem"] = "Aluno excluido com sucesso! ";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiCED/Controllers/CursoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiCED.Models;

namespace SiCED.Controllers
{
    public class CursoController : Controller
    {
        private ContextoEF db = new ContextoEF();

        // GET: Curso
        public ActionResult Index()
        {
            return View(db.Cursos.ToList());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursos.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Curso/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Cursos.Add(curso);
                db.SaveChanges();
                TempData["Mensagem"] = "Curso cadastrado com sucesso! ";
                return RedirectToAction("Index");
            }

            return View(curso);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursos.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(curso).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Curso atualizado com sucesso! ";
                return RedirectToAction("Index");
            }
            return View(curso);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Curso curso = db.Cursos.Find(id);
            if (curso == null)
            {
                return HttpNotFound();
            }
            return View(curso);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Curso curso = db.Cursos.Find(id);
            db.Cursos.Remove(curso);
            db.SaveChanges();
            TempData["Mensagem"] = "Curso excluido com sucesso! ";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiCED/Controllers/TurmaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiCED.Models;
using PagedList;
namespace SiCED.Controllers
{
    public class TurmaController : Controller
    {
        private ContextoEF db = new ContextoEF();

        // GET: Turma
        public ActionResult Index(int? pagina)
        {
            try
            {
                int tamanhopagina = 5;
                int numeroPagina = pagina ?? 1;

            var turmas = db.Turmas.Include(t => t.Curso).Include(t => t.Disciplina).Include(t => t.Professor);

                return View(turmas.OrderBy(p => p.Descricao).ToPagedList(numeroPagina, tamanhopagina));
            }
            catch(Exception err)
            {
                ViewBag.DetalheErros = err.Message.ToString();
                return View("Error");
            }
        }

        // GET: Turma/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // GET: Turma/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Nome");
            ViewBag.DisciplinaId = new SelectList(db.Disciplinas, "Id", "Nome");
            ViewBag.ProfessorId = new SelectList(db.Professores, "ProfessorId", "Nome");
            return View();
        }

        // POST: Turma/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descricao,ValorMensal,HorarioInicial,HorarioFinal,SegundaQuarta,SegundaQuartaSexta,TercaQuinta,TercaQuintaSexta,ProfessorId,CursoId,DisciplinaId")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                db.Turmas.Add(turma);
                db.SaveChanges();
                TempData["Mensagem"] = "Turma Cadastrado com sucesso! ";
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Nome", turma.CursoId);
            ViewBag.DisciplinaId = new SelectList(db.Disciplinas, "Id", "Nome", turma.DisciplinaId);
            ViewBag.ProfessorId = new SelectList(db.Professores, "ProfessorId", "Nome", turma.ProfessorId);
            return View(turma);
        }

        // GET: Turma/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Nome", turma.CursoId);
            ViewBag.DisciplinaId = new SelectList(db.Disciplinas, "Id", "Nome", turma.DisciplinaId);
            ViewBag.ProfessorId = new SelectList(db.Professores, "ProfessorId", "Nome", turma.ProfessorId);
            return View(turma);
        }

        // POST: Turma/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descricao,ValorMensal,HorarioInicial,HorarioFinal,SegundaQuarta,SegundaQuartaSexta,TercaQuinta,TercaQuintaSexta,ProfessorId,CursoId,DisciplinaId")] Turma turma)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turma).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Turma atualizada com sucesso! ";
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Nome", turma.CursoId);
            ViewBag.DisciplinaId = new SelectList(db.Disciplinas, "Id", "Nome", turma.DisciplinaId);
            ViewBag.ProfessorId = new SelectList(db.Professores, "ProfessorId", "Nome", turma.ProfessorId);
            return View(turma);
        }

        // GET: Turma/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = db.Turmas.Find(id);
            if (turma == null)
            {
                return HttpNotFound();
            }
            return View(turma);
        }

        // POST: Turma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Turma turma = db.Turmas.Find(id);
            db.Turmas.Remove(turma);
            db.SaveChanges();
            TempData["Mensagem"] = "Turma excluida com sucesso! ";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiCED/Areas/Administracao/Views/Shared/BreadcrumbsPartial.cshtml
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
           try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>

        @if (@Html.Action() == "Index")
        {
            <li class="active">
                <a href="@Url.Action("Index", @Html.Controller())">@Html.Controller()</a>
            </li>
        }
        else
        {
            <li>
                <a href="@Url.Action("Index", @Html.Controller())">@Html.Controller()</a>
            </li>
            <li class="active">@Html.Action()</li>
        }
    </ul><!-- /.breadcrumb -->

    
</div>

SiCED/Areas/Administracao/Views/Shared/CreateParaImpressão .cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AlunoId, "AlunoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlunoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlunoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurmaId, "TurmaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TurmaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurmaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeMatricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeMatricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeMatricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiCED/Areas/Administracao/Views/Shared/DetailsParaImpressao.cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutParaImpressao.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluno.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluno.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turma.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turma.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeMatricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeMatricula)
        </dd>

    </dl>
</div>

SiCED/Areas/Administracao/Views/Shared/FooterPartial.cshtml
<div class="footer">
    <div class="footer-inner">
        <div class="footer-content">
            <span class="bigger-120">
                <span class="blue bolder">Siced</span>
                 &copy; 2017
            </span>

            &nbsp; &nbsp;
            <span class="action-buttons">
                <a href="#">
                    <i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
                </a>

                <a href="#">
                    <i class="ace-icon fa fa-rss-square orange bigger-150"></i>
                </a>
            </span>
        </div>
    </div>
</div>

SiCED/Areas/Administracao/Views/Shared/NavigatorBarList.cshtml
<ul class="nav nav-list">

    <li class="">
        <a href="@Url.Action("Index", "Home")">
            <i class="menu-icon fa fa-pencil"></i>
            <span class="menu-text"> Página Principal </span>
        </a>

        <b class="arrow"></b>
    </li>


    <li class="">
        <a href="@Url.Action("Index", "Responsavel")">
            <i class="menu-icon fa fa-child"></i>
            Responsaveis
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="@Url.Action("Index", "Aluno")">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
                Alunos
            </span>

        </a>

        <b class="arrow"></b>


    </li>


    <li class="">
        <a href="@Url.Action("Index", "Matricula")">
            <i class="menu-icon fa fa-list-alt"></i>
            <span class="menu-text"> Matriculas </span>
        </a>

        <b class="arrow"></b>
    </li>


    @if (User.IsInRole("Administrador"))
    {


        <li class="">
            <a href="@Url.Action("Index", "Professor")">
                <i class="menu-icon fa fa-graduation-cap"></i>
                Professor
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="@Url.Action("Index", "Curso")">
                <i class="menu-icon fa fa-calendar"></i>

                <span class="menu-text">
                    Curso

                    <span class="badge badge-transparent tooltip-error" title="2 Important Events">
                        @*<i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>*@
                    </span>
                </span>
            </a>

            <b class="arrow"></b>
        </li>

        <li class="">
            <a href="@Url.Action("Index", "Disciplina")">
                <i class="menu-icon fa fa-picture-o"></i>
                <span class="menu-text"> Disciplinas </span>
            </a>

            <b class="arrow"></b>
        </li>


        <li class="">
            <a href="@Url.Action("Index", "Turma")">
                <i class="menu-icon fa fa-users"></i>
                Turma
            </a>

            <b class="arrow"></b>
        </li>

            <li class="">
                <a href="@Url.Action("Index", "UsersAdmin")">
                    <i class="menu-icon fa fa-lock"></i>
                    <span class="menu-text"> UsersAdmin </span>
                </a>

                <b class="arrow"></b>
            </li>


    }

    

  
</ul><!-- /.nav-list -->