SiCED/Models/Matricula.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SiCED.Models
{
    public class Matricula
    {
        public int Id { get; set; }
        public int AlunoId { get; set; }
        public int TurmaId { get; set; }
        //public int ProfessorId { get; set; }
        public DateTime DataDeMatricula { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual Aluno Aluno { get; set; }

        //public virtual Professor Professor { get; set; }

        //public virtual ICollection<Aluno> Aluno { get; set; }
        //public virtual ICollection<Turma> Turma { get; set; }
        
        
        

    }
}

SiCED/Areas/Administracao/Controllers/MatriculaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiCED.Models;
using PagedList;
using Rotativa;

namespace Areas.Administracao.Controllers
{

    public class MatriculaController : Controller
    {
        private ContextoEF db = new ContextoEF();

        public ActionResult GerarPDF(int id)
        {
            var modelo = db.Matriculas.Find(id);

            var pdf = new ViewAsPdf
            {
                ViewName = "DetailsParaImpressao",
                Model = modelo
            };

            return pdf;
        }


        public ActionResult ConsultarTurma(int? pagina, string NomeTurma = null)
        {
            int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;

            var matricula = (from a in db.Alunos
                             join m in db.Matriculas
                             on a.AlunoId equals m.AlunoId
                             join t in db.Turmas
                             on m.TurmaId equals t.Id
                              select m).ToList();


            if (!String.IsNullOrEmpty(NomeTurma))
            {
                matricula = matricula
                    .Where(x => 
                            x.Turma.Descricao.ToUpper()
                            .Contains(NomeTurma.ToUpper())).ToList();

            }

              return View("Index" , matricula.OrderBy(p => p.Turma.Descricao).ToPagedList(numeroPagina, tamanhoPagina));
        }



        // GET: Matricula
        public ActionResult Index(int? pagina)
        {
            try
            {
                int tamanhoPagina = 5;
                int numeroPagina = pagina ?? 1; 

            //var matriculas = db.Matriculas.Include(m => m.Aluno).Include(m => m.Turma);
            return View(db.Matriculas.OrderBy(p => p.DataDeMatricula).ToPagedList(numeroPagina, tamanhoPagina));
            }
            catch(Exception err)
            {
                ViewBag.DetalheErros = err.Message.ToString();
                return View("Error");
            }
        }

        // GET: Matricula/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // GET: Matricula/Create
        public ActionResult Create()
        {
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome");
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao");
            return View();
        }

        // POST: Matricula/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AlunoId,TurmaId,DataDeMatricula")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                db.Matriculas.Add(matricula);
                db.SaveChanges();
                TempData["Mensagem"] = "Matricula cadastrada com sucesso! ";
                return RedirectToAction("Index");
            }

            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // GET: Matricula/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // POST: Matricula/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AlunoId,TurmaId,DataDeMatricula")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(matricula).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Matricula atualizada com sucesso! ";
                return RedirectToAction("Index");
            }
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // GET: Matricula/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // POST: Matricula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Matricula matricula = db.Matriculas.Find(id);
            db.Matriculas.Remove(matricula);
            db.SaveChanges();
            TempData["Mensagem"] = "Matricula excluida com sucesso! ";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiCED/Controllers/MatriculaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiCED.Models;
using PagedList;
using Rotativa;

namespace SiCED.Controllers
{
    public class MatriculaController : Controller
    {
        private ContextoEF db = new ContextoEF();

        public ActionResult GerarPDF(int id)
        {
            var modelo = db.Matriculas.Find(id);

            var pdf = new ViewAsPdf
            {
                ViewName = "DetailsParaImpressao",
                Model = modelo
            };

            return pdf;
        }


        public ActionResult ConsultarTurma(int? pagina, string NomeTurma = null)
        {
            int tamanhoPagina = 5;
            int numeroPagina = pagina ?? 1;
            var turma = new Object();

            if (!String.IsNullOrEmpty(NomeTurma))
            {
                //turma = db.Matriculas
                //    .Where(f => f.Turma.Descricao.Contains(NomeTurma.ToUpper()))
                //    .OrderBy(f => f.Turma)
                //    .ToPagedList(numeroPagina, tamanhoPagina);

                turma = db.Matriculas.Include(t=>t.Turma)
                    .Where(m=>m.DataDeMatricula==DateTime.Now)
                    .ToPagedList(numeroPagina, tamanhoPagina);

            }
            else
            {
                turma = db.Matriculas.OrderBy(p => p.Turma.Descricao).ToPagedList(numeroPagina, tamanhoPagina);
            }
            return View("Index", turma);
        }



        // GET: Matricula
        public ActionResult Index(int? pagina)
        {
            try
            {
                int tamanhoPagina = 5;
                int numeroPagina = pagina ?? 1; 

            //var matriculas = db.Matriculas.Include(m => m.Aluno).Include(m => m.Turma);
            return View(db.Matriculas.OrderBy(p => p.DataDeMatricula).ToPagedList(numeroPagina, tamanhoPagina));
            }
            catch(Exception err)
            {
                ViewBag.DetalheErros = err.Message.ToString();
                return View("Error");
            }
        }

        // GET: Matricula/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // GET: Matricula/Create
        public ActionResult Create()
        {
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome");
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao");
            return View();
        }

        // POST: Matricula/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AlunoId,TurmaId,DataDeMatricula")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                db.Matriculas.Add(matricula);
                db.SaveChanges();
                TempData["Mensagem"] = "Matricula cadastrada com sucesso! ";
                return RedirectToAction("Index");
            }

            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // GET: Matricula/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // POST: Matricula/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AlunoId,TurmaId,DataDeMatricula")] Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(matricula).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Mensagem"] = "Matricula atualizada com sucesso! ";
                return RedirectToAction("Index");
            }
            ViewBag.AlunoId = new SelectList(db.Alunos, "AlunoId", "Nome", matricula.AlunoId);
            ViewBag.TurmaId = new SelectList(db.Turmas, "Id", "Descricao", matricula.TurmaId);
            return View(matricula);
        }

        // GET: Matricula/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matricula matricula = db.Matriculas.Find(id);
            if (matricula == null)
            {
                return HttpNotFound();
            }
            return View(matricula);
        }

        // POST: Matricula/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Matricula matricula = db.Matriculas.Find(id);
            db.Matriculas.Remove(matricula);
            db.SaveChanges();
            TempData["Mensagem"] = "Matricula excluida com sucesso! ";
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiCED/Areas/Administracao/Views/Matricula/Create.cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar Matricula</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AlunoId, "Aluno", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlunoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlunoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurmaId, "Turma", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TurmaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurmaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeMatricula,"Data de Matricula", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeMatricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeMatricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Matricular Aluno" class="btn btn-default" />

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquerymask")
    <script>
        $(document).ready(function () {
            $("#DataDeMatricula").datepicker()
                .mask("99/99/9999", { placeholder: "dd/mm/aaaa" });
                
    </script>
}

SiCED/Areas/Administracao/Views/Matricula/Delete.cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Tem certeza de que deseja excluir isso?</h3>
<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluno.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluno.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turma.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turma.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeMatricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeMatricula)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

SiCED/Areas/Administracao/Views/Matricula/Details.cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Matricula</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aluno.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aluno.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Turma.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Turma.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeMatricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeMatricula)
        </dd>

    </dl>
</div>
<div class="text-right"><a href="/Administracao/Matricula/GerarPDF/@Model.TurmaId"class="btn btn-danger"> Gerar Relatório em PDF</a></div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

SiCED/Areas/Administracao/Views/Matricula/Edit.cshtml
@model SiCED.Models.Matricula

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Matricula</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.AlunoId, "AlunoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlunoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlunoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurmaId, "TurmaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TurmaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurmaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeMatricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeMatricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeMatricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiCED/Areas/Administracao/Views/Matricula/Index.cshtml
@model PagedList.IPagedList<SiCED.Models.Matricula>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Matriculas</h2>

@using(Html.BeginForm("ConsultarTurma", "Matricula", FormMethod.Post, new { area = "Administracao" })) {
    <p>
        <input type="search" name="NomeTurma" />
        <input type="submit" value="Pesquisar" /> <input type="submit" value="Mostrar Todos" />
    </p>

}



<p>
    @Html.ActionLink("Cadastrar Matricula", "Create")
</p>

@if (TempData["Mensagem"] != null)
{
    <p class="alert-success">@TempData["Mensagem"]</p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Aluno")
        </th>
        <th>
            @Html.DisplayName("Turma")
        </th>
        <th>
            @Html.DisplayName("DataDeMatricula")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Aluno.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Turma.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataDeMatricula)
        </td>
        <td>
            <a href="@Url.Action("Edit", new { id=item.Id })" title="Editar" class="btn btn-info"><i class="glyphicon glyphicon-edit"></i></a>
            <a href="@Url.Action("Details", new { id=item.Id })" title="Detalhes" class="btn btn-warning"><i class="glyphicon glyphicon-eye-open"></i></a>
            <a href="@Url.Action("Delete", new { id=item.Id })" title="Excluir" class="btn btn-danger"><i class="glyphicon glyphicon-remove-circle"></i></a>
            @*@Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.Id }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.Id })*@
        </td>
    </tr>
}

</table>
Página @Model.PageNumber de @Model.PageNumber
@Html.PagedListPager(Model, Page => Url.Action("Index", new { pagina = Page}))